# -*- coding: utf-8 -*-
"""Aarit Fourier Transform Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJeJqaSd1SVe9v1MdtZ1QMEHVNNh50xE
"""

pip install pydub

import numpy as np
import matplotlib.pyplot as plt

from dataclasses import dataclass
from pydub import AudioSegment
from scipy.fft import rfft, rfftfreq
from scipy.io import wavfile

# USER SETTINGS

# Path to your MP3 file
AUDIO_PATH = "audio.mp3"

# Number of strongest Fourier components
TOP_N = 100

# Ignore frequencies below this value
MIN_FREQ = 20.0

# Maximum frequency analyzed/displayed
MAX_FREQ = 5000.0

# FFT window
# "hann" reduces spectral leakage
# "none" uses the original signal
WINDOW_TYPE = "hann"

def load_mp3(path):
    """
    Load an MP3 file and convert it into a normalized
    mono NumPy signal.

    Returns:
        sample_rate : samples per second
        signal      : normalized audio signal
    """

    # Load MP3
    audio = AudioSegment.from_mp3(path)

    # Get sample rate
    sample_rate = audio.frame_rate

    # Convert raw PCM samples into NumPy array
    data = np.array(
        audio.get_array_of_samples()
    )

    # --------------------------------------------------
    # Convert stereo → mono
    # --------------------------------------------------

    if audio.channels > 1:

        data = data.reshape(
            (-1, audio.channels)
        )

        data = data.mean(axis=1)

    # --------------------------------------------------
    # Convert integer PCM → floating point
    # --------------------------------------------------

    if np.issubdtype(
        data.dtype,
        np.integer
    ):

        info = np.iinfo(data.dtype)

        scale = max(
            abs(info.min),
            abs(info.max)
        )

        signal = (
            data.astype(np.float64)
            / scale
        )

    else:

        signal = data.astype(
            np.float64
        )


    # Remove DC offset


    signal -= np.mean(signal)


    # Normalize


    peak = np.max(
        np.abs(signal)
    )

    if peak > 0:
        signal /= peak

    return sample_rate, signal

sample_rate, signal = load_mp3(
    AUDIO_PATH
)

N = len(signal)

duration = N / sample_rate

time = (
    np.arange(N)
    / sample_rate
)

print("=" * 60)
print("AUDIO INFORMATION")
print("=" * 60)

print(f"File:              {AUDIO_PATH}")
print(f"Sample rate:       {sample_rate:,} Hz")
print(f"Samples:           {N:,}")
print(f"Duration:          {duration:.3f} seconds")
print(
    f"Nyquist frequency: "
    f"{sample_rate / 2:,.1f} Hz"
)
print(
    f"FFT resolution:    "
    f"{sample_rate / N:.6f} Hz"
)

x = 5 # Time in seconds

# Display first x seconds
display_time = min(
    x,
    duration
)

mask = time <= display_time

plt.figure(
    figsize=(12, 4)
)

plt.plot(
    time[mask],
    signal[mask]
)

plt.title(
    "Original MP3 Audio Waveform"
)

plt.xlabel(
    "Time (seconds)"
)

plt.ylabel(
    "Amplitude"
)

plt.grid(
    alpha=0.25
)

plt.show()

def create_window(
    length,
    window_type="hann"
):
    """
    Create the window applied before
    calculating the FFT.
    """

    if window_type == "hann":

        return np.hanning(
            length
        )

    elif window_type == "none":

        return np.ones(
            length
        )

    else:

        raise ValueError(
            "window_type must be "
            "'hann' or 'none'"
        )

# Commented out IPython magic to ensure Python compatibility.
def compute_fft(
    signal,
    sample_rate,
    window_type="hann"
):
    """
    Calculate the one-sided FFT.

    Returns:
        frequencies
        amplitudes
        phases
        spectrum
    """

    N = len(signal)

    # --------------------------------------------------
    # Apply window
    # --------------------------------------------------

    window = create_window(
        N,
        window_type
    )

    windowed_signal = (
        signal * window
    )

    # --------------------------------------------------
    # Fourier Transform
    # --------------------------------------------------

    spectrum = rfft(
        windowed_signal
    )

    # Frequency corresponding
    # to each FFT bin
    frequencies = rfftfreq(
        N,
        d=1 / sample_rate
    )

    # --------------------------------------------------
    # Calculate amplitudes
    # --------------------------------------------------

    coherent_gain = np.mean(
        window
    )

    amplitudes = (
        np.abs(spectrum)
        / (N * coherent_gain)
    )

    # rFFT contains only positive
    # frequencies, so double the
    # non-DC components.
    if N > 1:

        amplitudes[1:-1] *= 2

    # --------------------------------------------------
    # Calculate phase
    # --------------------------------------------------

    # FFT naturally produces:
    #
    # A cos(2πft + θ)
    #
    # We want:
    #
    # A sin(2πft + φ)
    #
    # Since:
    #
    # cos(x) = sin(x + π/2)
    #
    # φ = θ + π/2

    phases = (
        np.angle(spectrum)
        + np.pi / 2
    )

    # Keep phase between -π and π
    phases = (
        (phases + np.pi)
#         % (2 * np.pi)
        - np.pi
    )

    return (
        frequencies,
        amplitudes,
        phases,
        spectrum
    )

frequencies, amplitudes, phases, spectrum = (
    compute_fft(
        signal,
        sample_rate,
        WINDOW_TYPE
    )
)

print(
    f"FFT bins: {len(frequencies):,}"
)

print(
    f"Frequency resolution: "
    f"{sample_rate / N:.6f} Hz"
)

plt.figure(
    figsize=(12, 5)
)

plt.plot(
    frequencies,
    amplitudes
)

plt.xlim(
    0,
    min(
        MAX_FREQ,
        frequencies[-1]
    )
)

plt.title(
    "Fourier Frequency Spectrum"
)

plt.xlabel(
    "Frequency (Hz)"
)

plt.ylabel(
    "Amplitude"
)

plt.grid(
    alpha=0.25
)

plt.show()

@dataclass
class Wave:

    frequency: float
    amplitude: float
    phase: float
    fft_index: int

def get_dominant_waves(
    frequencies,
    amplitudes,
    phases,
    top_n=10,
    min_freq=20,
    max_freq=None
):
    """
    Find the strongest Fourier components
    within the selected frequency range.
    """

    if max_freq is None:

        max_freq = frequencies[-1]

    # Select valid frequencies
    valid = (
        (frequencies >= min_freq)
        & (frequencies <= max_freq)
        & (frequencies > 0)
    )

    valid_indices = (
        np.flatnonzero(valid)
    )

    if len(valid_indices) == 0:

        return []

    # Sort by amplitude
    sorted_indices = valid_indices[
        np.argsort(
            amplitudes[
                valid_indices
            ]
        )[::-1]
    ]

    # Select strongest components
    selected = (
        sorted_indices[:top_n]
    )

    waves = []

    for index in selected:

        waves.append(
            Wave(
                frequency=float(
                    frequencies[index]
                ),

                amplitude=float(
                    amplitudes[index]
                ),

                phase=float(
                    phases[index]
                ),

                fft_index=int(index)
            )
        )

    # Sort by frequency
    waves.sort(
        key=lambda wave:
        wave.frequency
    )

    return waves

waves = get_dominant_waves(
    frequencies,
    amplitudes,
    phases,
    top_n=TOP_N,
    min_freq=MIN_FREQ,
    max_freq=MAX_FREQ
)

print(
    f"Extracted {len(waves)} "
    f"dominant frequency components."
)

print(
    f"{'Wave':>6}"
    f"{'Frequency (Hz)':>20}"
    f"{'Amplitude':>15}"
    f"{'Phase (rad)':>15}"
)

print("-" * 60)

for i, wave in enumerate(
    waves,
    start=1
):

    print(
        f"{i:>6}"
        f"{wave.frequency:>20.3f}"
        f"{wave.amplitude:>15.6f}"
        f"{wave.phase:>15.6f}"
    )

def print_wave_functions(waves):

    print()
    print("=" * 75)
    print(
        "DOMINANT SINE WAVE FUNCTIONS"
    )
    print("=" * 75)

    print(
        "\nx(t) ≈ "
        "Σ Aᵢ sin(2π fᵢ t + φᵢ)\n"
    )

    for i, wave in enumerate(
        waves,
        start=1
    ):

        if wave.phase >= 0:

            sign = "+"
            phase = wave.phase

        else:

            sign = "-"
            phase = abs(
                wave.phase
            )

        print(
            f"Wave {i:2d}: "
            f"{wave.amplitude:.6f} × "
            f"sin(2π × "
            f"{wave.frequency:.3f} × t "
            f"{sign} {phase:.4f})"
        )

print_wave_functions(
    waves
)

def reconstruct_from_waves(
    waves,
    num_samples,
    sample_rate
):
    """
    Reconstruct the audio by directly summing
    the extracted sine functions.

    x(t) = Σ Aᵢ sin(2πfᵢt + φᵢ)
    """

    t = (
        np.arange(num_samples)
        / sample_rate
    )

    reconstructed = np.zeros(
        num_samples,
        dtype=np.float64
    )

    for wave in waves:

        reconstructed += (
            wave.amplitude
            * np.sin(
                2 * np.pi
                * wave.frequency
                * t
                + wave.phase
            )
        )

    return t, reconstructed

reconstructed_time, reconstructed = (
    reconstruct_from_waves(
        waves,
        N,
        sample_rate
    )
)

# Normalize only for visualization
peak = np.max(
    np.abs(reconstructed)
)

if peak > 1:

    reconstructed_plot = (
        reconstructed / peak
    )

else:

    reconstructed_plot = (
        reconstructed
    )

display_time = min(
    x,
    duration
)

original_mask = (
    time <= display_time
)

reconstructed_mask = (
    reconstructed_time
    <= display_time
)

plt.figure(
    figsize=(12, 5)
)

plt.plot(
    time[original_mask],
    signal[original_mask],
    label="Original MP3"
)

plt.plot(
    reconstructed_time[
        reconstructed_mask
    ],
    reconstructed_plot[
        reconstructed_mask
    ],
    label="Fourier Reconstruction"
)

plt.title(
    f"Original vs Fourier Reconstruction "
    f"({len(waves)} waves)"
)

plt.xlabel(
    "Time (seconds)"
)

plt.ylabel(
    "Amplitude"
)

plt.legend()

plt.grid(
    alpha=0.25
)

plt.show()

selected_frequencies = [
    wave.frequency
    for wave in waves
]

selected_amplitudes = [
    wave.amplitude
    for wave in waves
]

plt.figure(
    figsize=(12, 5)
)

plt.plot(
    frequencies,
    amplitudes,
    label="FFT Spectrum"
)

plt.scatter(
    selected_frequencies,
    selected_amplitudes,
    s=50,
    label="Selected Frequencies",
    zorder=3
)

plt.xlim(
    0,
    min(
        MAX_FREQ,
        frequencies[-1]
    )
)

plt.title(
    "Dominant Fourier Components"
)

plt.xlabel(
    "Frequency (Hz)"
)

plt.ylabel(
    "Amplitude"
)

plt.legend()

plt.grid(
    alpha=0.25
)

plt.show()

def calculate_error(
    original,
    reconstructed
):
    """
    Calculate MSE and RMSE.
    """

    error = (
        original
        - reconstructed
    )

    mse = np.mean(
        error ** 2
    )

    rmse = np.sqrt(
        mse
    )

    return mse, rmse

# Normalize reconstruction
reconstruction_peak = np.max(
    np.abs(reconstructed)
)

if reconstruction_peak > 0:

    reconstructed_normalized = (
        reconstructed
        / reconstruction_peak
    )

else:

    reconstructed_normalized = (
        reconstructed
    )

mse, rmse = calculate_error(
    signal,
    reconstructed_normalized
)

print(
    f"Mean Squared Error: "
    f"{mse:.8f}"
)

print(
    f"Root Mean Squared Error: "
    f"{rmse:.8f}"
)

def save_wav(
    path,
    sample_rate,
    signal
):
    """
    Save a floating-point signal
    as a 16-bit PCM WAV file.
    """

    signal = np.asarray(
        signal,
        dtype=np.float64
    )

    peak = np.max(
        np.abs(signal)
    )

    if peak > 0:

        signal = (
            signal / peak
        )

    signal = np.clip(
        signal,
        -1,
        1
    )

    pcm = np.round(
        signal * 32767
    ).astype(np.int16)

    wavfile.write(
        path,
        sample_rate,
        pcm
    )

OUTPUT_AUDIO = (
    "fourier_reconstruction.wav"
)

save_wav(
    OUTPUT_AUDIO,
    sample_rate,
    reconstructed
)

print(
    f"Saved reconstruction to: "
    f"{OUTPUT_AUDIO}"
)

def save_wave_functions(
    path,
    waves
):

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(
            "Fourier Audio Decomposition\n"
        )

        file.write(
            "=" * 60 + "\n\n"
        )

        file.write(
            "x(t) ≈ "
            "Σ Aᵢ sin(2π fᵢ t + φᵢ)\n\n"
        )

        for i, wave in enumerate(
            waves,
            start=1
        ):

            if wave.phase >= 0:

                sign = "+"
                phase = wave.phase

            else:

                sign = "-"
                phase = abs(
                    wave.phase
                )

            file.write(
                f"Wave {i}: "
                f"{wave.amplitude:.8f} × "
                f"sin(2π × "
                f"{wave.frequency:.6f} × t "
                f"{sign} {phase:.6f})\n"
            )

EQUATION_FILE = (
    "fourier_waves.txt"
)

save_wave_functions(
    EQUATION_FILE,
    waves
)

print(
    f"Saved equations to: "
    f"{EQUATION_FILE}"
)

wave_counts = [
    1,
    5,
    10,
    25,
    50,
    100
]

results = []

for count in wave_counts:

    test_waves = (
        get_dominant_waves(
            frequencies,
            amplitudes,
            phases,
            top_n=count,
            min_freq=MIN_FREQ,
            max_freq=MAX_FREQ
        )
    )

    _, test_reconstruction = (
        reconstruct_from_waves(
            test_waves,
            N,
            sample_rate
        )
    )

    # Normalize
    peak = np.max(
        np.abs(test_reconstruction)
    )

    if peak > 0:

        test_reconstruction /= peak

    _, test_rmse = (
        calculate_error(
            signal,
            test_reconstruction
        )
    )

    results.append(
        test_rmse
    )

    print(
        f"{count:3d} waves → "
        f"RMSE = {test_rmse:.6f}"
    )

plt.figure(
    figsize=(9, 5)
)

plt.plot(
    wave_counts,
    results,
    marker="o"
)

plt.title(
    "Reconstruction Error vs Number of Fourier Components"
)

plt.xlabel(
    "Number of sine waves"
)

plt.ylabel(
    "RMSE"
)

plt.grid(
    alpha=0.25
)

plt.show()

def build_equation(waves):

    terms = []

    for wave in waves:

        if wave.phase >= 0:

            sign = "+"
            phase = wave.phase

        else:

            sign = "-"
            phase = abs(
                wave.phase
            )

        term = (
            f"{wave.amplitude:.6f}"
            f"·sin(2π·"
            f"{wave.frequency:.3f}t "
            f"{sign} "
            f"{phase:.4f})"
        )

        terms.append(term)

    return (
        "x(t) ≈ "
        + " + ".join(terms)
    )

equation = build_equation(
    waves
)

print(equation)

print("=" * 70)
print("FOURIER AUDIO ANALYSIS COMPLETE")
print("=" * 70)

print("\nINPUT")
print(
    f"  File: {AUDIO_PATH}"
)
print(
    f"  Sample rate: "
    f"{sample_rate:,} Hz"
)
print(
    f"  Duration: "
    f"{duration:.3f} seconds"
)
print(
    f"  Samples: "
    f"{N:,}"
)

print("\nFOURIER MODEL")
print(
    f"  Components: "
    f"{len(waves)}"
)
print(
    f"  Frequency range: "
    f"{MIN_FREQ}–{MAX_FREQ} Hz"
)
print(
    f"  Resolution: "
    f"{sample_rate / N:.6f} Hz"
)

print("\nRECONSTRUCTION")
print(
    f"  RMSE: "
    f"{rmse:.8f}"
)

print("\nMATHEMATICAL FORM")
print(
    "  x(t) ≈ "
    "Σ Aᵢ sin(2πfᵢt + φᵢ)"
)

def reconstruct_from_waves(waves, num_samples, sample_rate):
    t = np.arange(num_samples) / sample_rate
    reconstruction = np.zeros(num_samples, dtype=float)

    for wave in waves:
        reconstruction += wave.amplitude * np.sin(
            2 * np.pi * wave.frequency * t + wave.phase
        )

    return reconstruction

# Compare all Fourier reconstruction settings in one figure

component_counts = [1, 5, 10, 25, 50, 100]

# Make sure we have enough Fourier components
max_components = min(100, len(waves))

# Only test values that actually exist
component_counts = [
    K for K in component_counts
    if K <= max_components
]

# Use a short interval so the oscillations are visible
display_time = min(0.05, duration)
mask = time <= display_time

fig, axes = plt.subplots(
    2, 3,
    figsize=(15, 8),
    sharex=True,
    sharey=True
)

axes = axes.flatten()

for ax, K in zip(axes, component_counts):

    # Select K Fourier components
    waves_K = waves[:K]

    # IMPORTANT: use len(signal), not N
    reconstruction_K = reconstruct_from_waves(
        waves_K,
        len(signal),
        sample_rate
    )

    # Plot original signal
    ax.plot(
        time[mask],
        signal[mask],
        label="Original"
    )

    # Plot reconstruction
    ax.plot(
        time[mask],
        reconstruction_K[mask],
        label=f"K = {K}"
    )

    ax.set_title(f"{K} Fourier Components")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude")
    ax.grid(True)
    ax.legend()

fig.suptitle(
    "Effect of the Number of Fourier Components on Sound Reconstruction",
    fontsize=16
)

plt.tight_layout()
plt.show()